### ISSUE TITLE
network_plugin_mode expects "Overlay" but azurerm provider expect "overlay" resulting in constant cluster destroy

### ISSUE THREAD

**Issue by daximillian** [Azure/terraform-azurerm-aks#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.4

### Module Version

7.2.0

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
network_plugin                    = "azure"
  network_plugin_mode               = "Overlay"    
  ebpf_data_plane                   = "cilium"
```

### tfvars variables values

```hcl
N/A
```

### Debug Output/Panic Output

```shell
network_profile {
          + network_mode        = (known after apply)
          ~ network_plugin_mode = "overlay" -> "Overlay" # forces replacement
          ~ network_policy      = "cilium" -> (known after apply)
          ~ pod_cidr            = "10.244.0.0/16" -> (known after apply)
          ~ pod_cidrs           = [
              - "10.244.0.0/16",
            ] -> (known after apply)
```

### Expected Behaviour

Not have the capitalization of the network_plugin_mode force a replacement.

### Actual Behaviour

Setting the network_plugin_mode to "Overlay" forces a replacement, and setting it to "overlay" results in an error.

**Comment by zioproto** [comment]
hello @daximillian ,
this is a provider issue, and should be opened on the repo https://github.com/hashicorp/terraform-provider-azurerm

I checked, and the issue has already been fixed with provider version **v3.66.0**
https://github.com/hashicorp/terraform-provider-azurerm/issues/22621

I see you are using provider version 3.64.0, please upgrade

**Comment by zioproto** [comment]
Should we upgrade the requirement to v3.66.0 if using Overlay ?

https://github.com/Azure/terraform-azurerm-aks/blob/0833586b9a22b683fcd1a774372956ae8f9da5ba/versions.tf#L9-L12

**Comment by lonegunmanb** [comment]
> Should we upgrade the requirement to v3.66.0 if using Overlay ?
> 
> https://github.com/Azure/terraform-azurerm-aks/blob/0833586b9a22b683fcd1a774372956ae8f9da5ba/versions.tf#L9-L12

Good idea!

**Comment by lonegunmanb** [comment]
Hi

> Should we upgrade the requirement to v3.66.0 if using Overlay ?
> 
> https://github.com/Azure/terraform-azurerm-aks/blob/0833586b9a22b683fcd1a774372956ae8f9da5ba/versions.tf#L9-L12

After reading the [issue comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/22621#issuecomment-1644998536)

>The latest release v3.66.0 shipped a documentation fix to the casing of the value in https://github.com/hashicorp/terraform-provider-azurerm/pull/22554.

v3.66.0 only fixed the document, so now the user must use `overlay` instead of `Overlay` @daximillian .

**Comment by daximillian** [comment]
I have upgraded to provider 3.79.0 and to module version 7.4.0. 
The bug remains, it just isn't forcing a cluster replacement, it's just doing a cluster update _every single time_. 
When the module receives "overlay" it outputs the following error:

```
╷
│ Error: Resource precondition failed
│ 
│   on .terraform/modules/test2_aks/main.tf line 523, in resource "azurerm_kubernetes_cluster" "main":
│  523:       condition     = var.ebpf_data_plane != "cilium" || var.network_plugin_mode == "Overlay" || var.pod_subnet_id != null
│     ├────────────────
│     │ var.ebpf_data_plane is "cilium"
│     │ var.network_plugin_mode is "overlay"
│     │ var.pod_subnet_id is null
│ 
│ When ebpf_data_plane is set to cilium, one of either network_plugin_mode = `Overlay` or pod_subnet_id must be specified.
╵
```

When the module receives "Overlay" it forces an update:

```
Terraform will perform the following actions:

  # module.test2_aks.azurerm_kubernetes_cluster.main will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "main" {
        id                                  = "********"
        name                                = "test2-aks"
        tags                                = {
            "env"        = "test2"
            "managed_by" = "terraform"
            "name"       = "test2-aks"
        }
        # (32 unchanged attributes hidden)

      ~ network_profile {
          ~ network_plugin_mode = "overlay" -> "Overlay"
            # (11 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (11 unchanged blocks hidden)
    }

```

Please change the condition of the module to specify "overlay" and not "Overlay" so that we can specify the correct value and not have our cluster updated with no need.

**Comment by lonegunmanb** [comment]
I think this issue has been fix by #472 so I'm closing it now, please feel free to reopen it if you still meet the error after you've upgraded to `v7.5.0` @daximillian .
